name: Deploy
on: push
jobs:
  Build-Artifact:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v1
        name: Checkout repository
      - uses: krdlab/setup-haxe@master
        name: Fetch Haxe nightly
        with:
            haxe-version: 4.3.7
      - name: Setup environment
        run: |
          sed -i 's/git@github.com:/https:\/\/github.com\//g' .gitmodules
          make init
          make prod
      - uses: actions/upload-pages-artifact@v3
        id: artifact-upload
        with:
            path: bin/js
  Publish-Page:
    runs-on: ubuntu-latest
    needs: Build-Artifact
    permissions:
        pages: write
        id-token: write
    environment: 
        name: github-pages
        url: ${{steps.deployment.outputs.page_url}}
    steps:
      - uses: actions/deploy-pages@v4
        id: deployment
        name: Deploy Page
